---
apiVersion: v1
kind: Pod
metadata: 
  name: init-demo
  labels:
    app: nginx
    purpose: initdemp
spec:
  initcontainers:
    - name: init1
      image: alpine
      command:
        - sleep
        - 5s
    - name: init2
      image: alpine
      command:
        - sleep
        - 10s
  containers:
    - name: webserver
      image: nginx:1.25
     

